# Generated by Django 2.2.13 on 2020-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=12345, max_length=90),
            preserve_default=False,
        ),
    ]
