# Generated by Django 2.2.13 on 2020-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wasteMGT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waste',
            name='pickup_lat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='waste',
            name='pickup_long',
            field=models.IntegerField(),
        ),
    ]
